// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiBQ9wneMBxnlppjV4nfOcLnZkQwYCI8',
    appId: '1:170570584621:web:a5b49f7129dec1263e1ea4',
    messagingSenderId: '170570584621',
    projectId: 'btshortstay',
    authDomain: 'btshortstay.firebaseapp.com',
    storageBucket: 'btshortstay.firebasestorage.app',
    measurementId: 'G-SE5KF532H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhiI6qZxjf5B8HLSmuupj_1LrbggSuVeo',
    appId: '1:170570584621:android:503685326bbc98c43e1ea4',
    messagingSenderId: '170570584621',
    projectId: 'btshortstay',
    storageBucket: 'btshortstay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAyK8PxsR8d7anti925xzFzYsFjtDtII',
    appId: '1:170570584621:ios:7ffddc507c30c23f3e1ea4',
    messagingSenderId: '170570584621',
    projectId: 'btshortstay',
    storageBucket: 'btshortstay.firebasestorage.app',
    iosBundleId: 'com.example.btshorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfAyK8PxsR8d7anti925xzFzYsFjtDtII',
    appId: '1:170570584621:ios:7ffddc507c30c23f3e1ea4',
    messagingSenderId: '170570584621',
    projectId: 'btshortstay',
    storageBucket: 'btshortstay.firebasestorage.app',
    iosBundleId: 'com.example.btshorts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJiBQ9wneMBxnlppjV4nfOcLnZkQwYCI8',
    appId: '1:170570584621:web:cfae033c163a0c9f3e1ea4',
    messagingSenderId: '170570584621',
    projectId: 'btshortstay',
    authDomain: 'btshortstay.firebaseapp.com',
    storageBucket: 'btshortstay.firebasestorage.app',
    measurementId: 'G-78LEVWYS36',
  );
}

/// storageBucket: 'btshortstay.firebasestorage.app......btshortstay.firebaseapp.com'